// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/controlplane/v1/controlplane.proto

package controlplanev1

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// Ensure the protobuf package is imported
var _ = proto.Marshal

// AgentLifecycleState represents the lifecycle state of an agent
type AgentLifecycleState int32

const (
	AgentLifecycleState_AGENT_LIFECYCLE_STATE_UNSPECIFIED AgentLifecycleState = 0
	AgentLifecycleState_AGENT_LIFECYCLE_STATE_ONLINE     AgentLifecycleState = 1
	AgentLifecycleState_AGENT_LIFECYCLE_STATE_DEGRADED   AgentLifecycleState = 2
	AgentLifecycleState_AGENT_LIFECYCLE_STATE_OFFLINE    AgentLifecycleState = 3
)

var AgentLifecycleState_name = map[int32]string{
	0: "AGENT_LIFECYCLE_STATE_UNSPECIFIED",
	1: "AGENT_LIFECYCLE_STATE_ONLINE",
	2: "AGENT_LIFECYCLE_STATE_DEGRADED",
	3: "AGENT_LIFECYCLE_STATE_OFFLINE",
}

var AgentLifecycleState_value = map[string]int32{
	"AGENT_LIFECYCLE_STATE_UNSPECIFIED": 0,
	"AGENT_LIFECYCLE_STATE_ONLINE":     1,
	"AGENT_LIFECYCLE_STATE_DEGRADED":   2,
	"AGENT_LIFECYCLE_STATE_OFFLINE":    3,
}

func (x AgentLifecycleState) String() string {
	return AgentLifecycleState_name[int32(x)]
}

// SiteConnectivityState represents the connectivity state of a site
type SiteConnectivityState int32

const (
	SiteConnectivityState_SITE_CONNECTIVITY_STATE_UNSPECIFIED SiteConnectivityState = 0
	SiteConnectivityState_SITE_CONNECTIVITY_STATE_ONLINE      SiteConnectivityState = 1
	SiteConnectivityState_SITE_CONNECTIVITY_STATE_PARTIAL     SiteConnectivityState = 2
	SiteConnectivityState_SITE_CONNECTIVITY_STATE_OFFLINE     SiteConnectivityState = 3
)

var SiteConnectivityState_name = map[int32]string{
	0: "SITE_CONNECTIVITY_STATE_UNSPECIFIED",
	1: "SITE_CONNECTIVITY_STATE_ONLINE",
	2: "SITE_CONNECTIVITY_STATE_PARTIAL",
	3: "SITE_CONNECTIVITY_STATE_OFFLINE",
}

var SiteConnectivityState_value = map[string]int32{
	"SITE_CONNECTIVITY_STATE_UNSPECIFIED": 0,
	"SITE_CONNECTIVITY_STATE_ONLINE":      1,
	"SITE_CONNECTIVITY_STATE_PARTIAL":     2,
	"SITE_CONNECTIVITY_STATE_OFFLINE":     3,
}

func (x SiteConnectivityState) String() string {
	return SiteConnectivityState_name[int32(x)]
}

// PlanStatus represents the status of a plan
type PlanStatus int32

const (
	PlanStatus_PLAN_STATUS_UNSPECIFIED PlanStatus = 0
	PlanStatus_PLAN_STATUS_PENDING     PlanStatus = 1
	PlanStatus_PLAN_STATUS_IN_PROGRESS PlanStatus = 2
	PlanStatus_PLAN_STATUS_SUCCEEDED   PlanStatus = 3
	PlanStatus_PLAN_STATUS_FAILED      PlanStatus = 4
	PlanStatus_PLAN_STATUS_CANCELLED   PlanStatus = 5
)

var PlanStatus_name = map[int32]string{
	0: "PLAN_STATUS_UNSPECIFIED",
	1: "PLAN_STATUS_PENDING",
	2: "PLAN_STATUS_IN_PROGRESS",
	3: "PLAN_STATUS_SUCCEEDED",
	4: "PLAN_STATUS_FAILED",
	5: "PLAN_STATUS_CANCELLED",
}

var PlanStatus_value = map[string]int32{
	"PLAN_STATUS_UNSPECIFIED": 0,
	"PLAN_STATUS_PENDING":     1,
	"PLAN_STATUS_IN_PROGRESS": 2,
	"PLAN_STATUS_SUCCEEDED":   3,
	"PLAN_STATUS_FAILED":      4,
	"PLAN_STATUS_CANCELLED":   5,
}

func (x PlanStatus) String() string {
	return PlanStatus_name[int32(x)]
}

// MicroVMOperation represents a microVM operation
type MicroVMOperation int32

const (
	MicroVMOperation_MICRO_VM_OPERATION_UNSPECIFIED MicroVMOperation = 0
	MicroVMOperation_MICRO_VM_OPERATION_CREATE      MicroVMOperation = 1
	MicroVMOperation_MICRO_VM_OPERATION_START       MicroVMOperation = 2
	MicroVMOperation_MICRO_VM_OPERATION_STOP        MicroVMOperation = 3
	MicroVMOperation_MICRO_VM_OPERATION_DELETE      MicroVMOperation = 4
)

var MicroVMOperation_name = map[int32]string{
	0: "MICRO_VM_OPERATION_UNSPECIFIED",
	1: "MICRO_VM_OPERATION_CREATE",
	2: "MICRO_VM_OPERATION_START",
	3: "MICRO_VM_OPERATION_STOP",
	4: "MICRO_VM_OPERATION_DELETE",
}

var MicroVMOperation_value = map[string]int32{
	"MICRO_VM_OPERATION_UNSPECIFIED": 0,
	"MICRO_VM_OPERATION_CREATE":      1,
	"MICRO_VM_OPERATION_START":       2,
	"MICRO_VM_OPERATION_STOP":        3,
	"MICRO_VM_OPERATION_DELETE":      4,
}

func (x MicroVMOperation) String() string {
	return MicroVMOperation_name[int32(x)]
}

// MicroVMState represents the state of a microVM
type MicroVMState int32

const (
	MicroVMState_MICRO_VM_STATE_UNSPECIFIED MicroVMState = 0
	MicroVMState_MICRO_VM_STATE_CREATING    MicroVMState = 1
	MicroVMState_MICRO_VM_STATE_STOPPED     MicroVMState = 2
	MicroVMState_MICRO_VM_STATE_RUNNING     MicroVMState = 3
	MicroVMState_MICRO_VM_STATE_DELETING    MicroVMState = 4
	MicroVMState_MICRO_VM_STATE_ERROR       MicroVMState = 5
)

var MicroVMState_name = map[int32]string{
	0: "MICRO_VM_STATE_UNSPECIFIED",
	1: "MICRO_VM_STATE_CREATING",
	2: "MICRO_VM_STATE_STOPPED",
	3: "MICRO_VM_STATE_RUNNING",
	4: "MICRO_VM_STATE_DELETING",
	5: "MICRO_VM_STATE_ERROR",
}

var MicroVMState_value = map[string]int32{
	"MICRO_VM_STATE_UNSPECIFIED": 0,
	"MICRO_VM_STATE_CREATING":    1,
	"MICRO_VM_STATE_STOPPED":     2,
	"MICRO_VM_STATE_RUNNING":     3,
	"MICRO_VM_STATE_DELETING":    4,
	"MICRO_VM_STATE_ERROR":       5,
}

func (x MicroVMState) String() string {
	return MicroVMState_name[int32(x)]
}

// ExecutionState represents the state of an execution
type ExecutionState int32

const (
	ExecutionState_EXECUTION_STATE_UNSPECIFIED ExecutionState = 0
	ExecutionState_EXECUTION_STATE_PENDING     ExecutionState = 1
	ExecutionState_EXECUTION_STATE_IN_PROGRESS ExecutionState = 2
	ExecutionState_EXECUTION_STATE_SUCCEEDED   ExecutionState = 3
	ExecutionState_EXECUTION_STATE_FAILED      ExecutionState = 4
)

var ExecutionState_name = map[int32]string{
	0: "EXECUTION_STATE_UNSPECIFIED",
	1: "EXECUTION_STATE_PENDING",
	2: "EXECUTION_STATE_IN_PROGRESS",
	3: "EXECUTION_STATE_SUCCEEDED",
	4: "EXECUTION_STATE_FAILED",
}

var ExecutionState_value = map[string]int32{
	"EXECUTION_STATE_UNSPECIFIED": 0,
	"EXECUTION_STATE_PENDING":     1,
	"EXECUTION_STATE_IN_PROGRESS": 2,
	"EXECUTION_STATE_SUCCEEDED":   3,
	"EXECUTION_STATE_FAILED":      4,
}

func (x ExecutionState) String() string {
	return ExecutionState_name[int32(x)]
}

// LogSeverity represents log severity levels
type LogSeverity int32

const (
	LogSeverity_LOG_SEVERITY_UNSPECIFIED LogSeverity = 0
	LogSeverity_LOG_SEVERITY_DEBUG       LogSeverity = 1
	LogSeverity_LOG_SEVERITY_INFO        LogSeverity = 2
	LogSeverity_LOG_SEVERITY_WARN        LogSeverity = 3
	LogSeverity_LOG_SEVERITY_ERROR       LogSeverity = 4
)

var LogSeverity_name = map[int32]string{
	0: "LOG_SEVERITY_UNSPECIFIED",
	1: "LOG_SEVERITY_DEBUG",
	2: "LOG_SEVERITY_INFO",
	3: "LOG_SEVERITY_WARN",
	4: "LOG_SEVERITY_ERROR",
}

var LogSeverity_value = map[string]int32{
	"LOG_SEVERITY_UNSPECIFIED": 0,
	"LOG_SEVERITY_DEBUG":       1,
	"LOG_SEVERITY_INFO":        2,
	"LOG_SEVERITY_WARN":        3,
	"LOG_SEVERITY_ERROR":       4,
}

func (x LogSeverity) String() string {
	return LogSeverity_name[int32(x)]
}

// EnrollRequest is the request for agent enrollment
type EnrollRequest struct {
	EnrollmentToken   string            `json:"enrollment_token,omitempty"`
	AgentVersion      string            `json:"agent_version,omitempty"`
	RequestedHostname string            `json:"requested_hostname,omitempty"`
	HostFingerprint   *HostFingerprint  `json:"host_fingerprint,omitempty"`
	CsrPem            string            `json:"csr_pem,omitempty"`
	Labels            map[string]string `json:"labels,omitempty"`
	BootstrapNonce    string            `json:"bootstrap_nonce,omitempty"`
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
}

func (x *EnrollRequest) String() string {
	return fmt.Sprintf("EnrollRequest{Token: %s}", x.EnrollmentToken)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

func (x *EnrollRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *EnrollRequest) GetRequestedHostname() string {
	if x != nil {
		return x.RequestedHostname
	}
	return ""
}

func (x *EnrollRequest) GetHostFingerprint() *HostFingerprint {
	if x != nil {
		return x.HostFingerprint
	}
	return nil
}

func (x *EnrollRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

func (x *EnrollRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *EnrollRequest) GetBootstrapNonce() string {
	if x != nil {
		return x.BootstrapNonce
	}
	return ""
}

// EnrollResponse is the response for agent enrollment
type EnrollResponse struct {
	TenantId                 string `json:"tenant_id,omitempty"`
	SiteId                   string `json:"site_id,omitempty"`
	HostId                   string `json:"host_id,omitempty"`
	AgentId                  string `json:"agent_id,omitempty"`
	ClientCertificatePem     string `json:"client_certificate_pem,omitempty"`
	CaCertificatePem         string `json:"ca_certificate_pem,omitempty"`
	RefreshToken             string `json:"refresh_token,omitempty"`
	HeartbeatEndpoint        string `json:"heartbeat_endpoint,omitempty"`
	HeartbeatIntervalSeconds int32  `json:"heartbeat_interval_seconds,omitempty"`
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
}

func (x *EnrollResponse) String() string {
	return fmt.Sprintf("EnrollResponse{AgentID: %s}", x.AgentId)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EnrollResponse) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *EnrollResponse) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *EnrollResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *EnrollResponse) GetClientCertificatePem() string {
	if x != nil {
		return x.ClientCertificatePem
	}
	return ""
}

func (x *EnrollResponse) GetCaCertificatePem() string {
	if x != nil {
		return x.CaCertificatePem
	}
	return ""
}

func (x *EnrollResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *EnrollResponse) GetHeartbeatEndpoint() string {
	if x != nil {
		return x.HeartbeatEndpoint
	}
	return ""
}

func (x *EnrollResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

// HostFingerprint represents host fingerprinting information
type HostFingerprint struct {
	MachineIdSha256  string `json:"machine_id_sha256,omitempty"`
	BiosUuidSha256   string `json:"bios_uuid_sha256,omitempty"`
	PrimaryMacSha256 string `json:"primary_mac_sha256,omitempty"`
}

func (x *HostFingerprint) Reset() { *x = HostFingerprint{} }
func (*HostFingerprint) ProtoMessage() {}

func (x *HostFingerprint) GetMachineIdSha256() string {
	if x != nil {
		return x.MachineIdSha256
	}
	return ""
}

// HeartbeatRequest is the request for agent heartbeat
type HeartbeatRequest struct {
	TenantId          string                 `json:"tenant_id,omitempty"`
	SiteId            string                 `json:"site_id,omitempty"`
	HostId            string                 `json:"host_id,omitempty"`
	AgentId           string                 `json:"agent_id,omitempty"`
	HeartbeatSeq      int64                  `json:"heartbeat_seq,omitempty"`
	SentAt            *timestamppb.Timestamp `json:"sent_at,omitempty"`
	AgentStatus       *AgentStatus           `json:"agent_status,omitempty"`
	HostFacts         *HostFacts             `json:"host_facts,omitempty"`
	NetbirdStatus     *NetBirdPeerStatus     `json:"netbird_status,omitempty"`
	Microvms          []*MicroVMStatus       `json:"microvms,omitempty"`
	ExecutionUpdates  []*ExecutionUpdate     `json:"execution_updates,omitempty"`
}

func (x *HeartbeatRequest) Reset() { *x = HeartbeatRequest{} }
func (x *HeartbeatRequest) String() string { return fmt.Sprintf("HeartbeatRequest{AgentID: %s}", x.AgentId) }
func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) GetTenantId() string { if x != nil { return x.TenantId }; return "" }
func (x *HeartbeatRequest) GetSiteId() string   { if x != nil { return x.SiteId }; return "" }
func (x *HeartbeatRequest) GetHostId() string   { if x != nil { return x.HostId }; return "" }
func (x *HeartbeatRequest) GetAgentId() string  { if x != nil { return x.AgentId }; return "" }
func (x *HeartbeatRequest) GetHeartbeatSeq() int64 { if x != nil { return x.HeartbeatSeq }; return 0 }
func (x *HeartbeatRequest) GetAgentStatus() *AgentStatus { if x != nil { return x.AgentStatus }; return nil }
func (x *HeartbeatRequest) GetHostFacts() *HostFacts { if x != nil { return x.HostFacts }; return nil }
func (x *HeartbeatRequest) GetMicrovms() []*MicroVMStatus { if x != nil { return x.Microvms }; return nil }
func (x *HeartbeatRequest) GetExecutionUpdates() []*ExecutionUpdate { if x != nil { return x.ExecutionUpdates }; return nil }

// HeartbeatResponse is the response for agent heartbeat
type HeartbeatResponse struct {
	NextHeartbeatSeconds int32   `json:"next_heartbeat_seconds,omitempty"`
	PendingPlans         []*Plan `json:"pending_plans,omitempty"`
	RotateCertificate    bool    `json:"rotate_certificate,omitempty"`
}

func (x *HeartbeatResponse) Reset() { *x = HeartbeatResponse{} }
func (x *HeartbeatResponse) String() string { return "HeartbeatResponse{}" }
func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) GetNextHeartbeatSeconds() int32 { if x != nil { return x.NextHeartbeatSeconds }; return 0 }
func (x *HeartbeatResponse) GetPendingPlans() []*Plan { if x != nil { return x.PendingPlans }; return nil }
func (x *HeartbeatResponse) GetRotateCertificate() bool { if x != nil { return x.RotateCertificate }; return false }

// AgentStatus represents agent status
type AgentStatus struct {
	Version       string                 `json:"version,omitempty"`
	Os            string                 `json:"os,omitempty"`
	Arch          string                 `json:"arch,omitempty"`
	KernelVersion string                 `json:"kernel_version,omitempty"`
	State         AgentLifecycleState    `json:"state,omitempty"`
	StartedAt     *timestamppb.Timestamp `json:"started_at,omitempty"`
}

func (x *AgentStatus) Reset() { *x = AgentStatus{} }
func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) GetVersion() string       { if x != nil { return x.Version }; return "" }
func (x *AgentStatus) GetOs() string            { if x != nil { return x.Os }; return "" }
func (x *AgentStatus) GetArch() string          { if x != nil { return x.Arch }; return "" }
func (x *AgentStatus) GetKernelVersion() string { if x != nil { return x.KernelVersion }; return "" }
func (x *AgentStatus) GetState() AgentLifecycleState { if x != nil { return x.State }; return AgentLifecycleState_AGENT_LIFECYCLE_STATE_UNSPECIFIED }

// HostFacts represents host facts
type HostFacts struct {
	CpuCoresTotal            uint32 `json:"cpu_cores_total,omitempty"`
	MemoryBytesTotal         uint64 `json:"memory_bytes_total,omitempty"`
	MemoryBytesFree          uint64 `json:"memory_bytes_free,omitempty"`
	StorageBytesTotal        uint64 `json:"storage_bytes_total,omitempty"`
	StorageBytesFree         uint64 `json:"storage_bytes_free,omitempty"`
	KvmAvailable             bool   `json:"kvm_available,omitempty"`
	CloudHypervisorAvailable bool   `json:"cloud_hypervisor_available,omitempty"`
}

func (x *HostFacts) Reset() { *x = HostFacts{} }
func (*HostFacts) ProtoMessage() {}

func (x *HostFacts) GetCpuCoresTotal() uint32    { if x != nil { return x.CpuCoresTotal }; return 0 }
func (x *HostFacts) GetMemoryBytesTotal() uint64 { if x != nil { return x.MemoryBytesTotal }; return 0 }
func (x *HostFacts) GetKvmAvailable() bool       { if x != nil { return x.KvmAvailable }; return false }

// NetBirdPeerStatus represents NetBird peer status
type NetBirdPeerStatus struct {
	PeerId        string                 `json:"peer_id,omitempty"`
	Connected     bool                   `json:"connected,omitempty"`
	ManagementUrl string                 `json:"management_url,omitempty"`
	NetworkId     string                 `json:"network_id,omitempty"`
	Ipv4          string                 `json:"ipv4,omitempty"`
	CheckedAt     *timestamppb.Timestamp `json:"checked_at,omitempty"`
}

func (x *NetBirdPeerStatus) Reset() { *x = NetBirdPeerStatus{} }
func (*NetBirdPeerStatus) ProtoMessage() {}

// ApplyPlanRequest is the request for applying a plan
type ApplyPlanRequest struct {
	SiteId            string           `json:"site_id,omitempty"`
	RequestedByUserId string           `json:"requested_by_user_id,omitempty"`
	IdempotencyKey    string           `json:"idempotency_key,omitempty"`
	ClientRequestId   string           `json:"client_request_id,omitempty"`
	Operations        []*PlanOperation `json:"operations,omitempty"`
	DryRun            bool             `json:"dry_run,omitempty"`
}

func (x *ApplyPlanRequest) Reset() { *x = ApplyPlanRequest{} }
func (x *ApplyPlanRequest) String() string { return fmt.Sprintf("ApplyPlanRequest{SiteID: %s}", x.SiteId) }
func (*ApplyPlanRequest) ProtoMessage() {}

func (x *ApplyPlanRequest) GetSiteId() string { if x != nil { return x.SiteId }; return "" }
func (x *ApplyPlanRequest) GetIdempotencyKey() string { if x != nil { return x.IdempotencyKey }; return "" }
func (x *ApplyPlanRequest) GetOperations() []*PlanOperation { if x != nil { return x.Operations }; return nil }

// ApplyPlanResponse is the response for applying a plan
type ApplyPlanResponse struct {
	PlanId       string     `json:"plan_id,omitempty"`
	PlanVersion  uint64     `json:"plan_version,omitempty"`
	PlanStatus   PlanStatus `json:"plan_status,omitempty"`
	Deduplicated bool       `json:"deduplicated,omitempty"`
}

func (x *ApplyPlanResponse) Reset() { *x = ApplyPlanResponse{} }
func (*ApplyPlanResponse) ProtoMessage() {}

func (x *ApplyPlanResponse) GetPlanId() string      { if x != nil { return x.PlanId }; return "" }
func (x *ApplyPlanResponse) GetPlanVersion() uint64 { if x != nil { return x.PlanVersion }; return 0 }
func (x *ApplyPlanResponse) GetPlanStatus() PlanStatus { if x != nil { return x.PlanStatus }; return PlanStatus_PLAN_STATUS_UNSPECIFIED }
func (x *ApplyPlanResponse) GetDeduplicated() bool  { if x != nil { return x.Deduplicated }; return false }

// Plan represents a plan
type Plan struct {
	PlanId         string           `json:"plan_id,omitempty"`
	PlanVersion    uint64           `json:"plan_version,omitempty"`
	SiteId         string           `json:"site_id,omitempty"`
	IdempotencyKey string           `json:"idempotency_key,omitempty"`
	Operations     []*PlanOperation `json:"operations,omitempty"`
	CreatedAt      *timestamppb.Timestamp `json:"created_at,omitempty"`
}

func (x *Plan) Reset() { *x = Plan{} }
func (*Plan) ProtoMessage() {}

func (x *Plan) GetPlanId() string                { if x != nil { return x.PlanId }; return "" }
func (x *Plan) GetOperations() []*PlanOperation { if x != nil { return x.Operations }; return nil }

// PlanOperation represents a plan operation
type PlanOperation struct {
	OperationId    string               `json:"operation_id,omitempty"`
	VmId           string               `json:"vm_id,omitempty"`
	Operation      MicroVMOperation     `json:"operation,omitempty"`
	CreateConfig   *CreateMicroVMConfig `json:"create_config,omitempty"`
	TimeoutSeconds uint32               `json:"timeout_seconds,omitempty"`
}

func (x *PlanOperation) Reset() { *x = PlanOperation{} }
func (*PlanOperation) ProtoMessage() {}

func (x *PlanOperation) GetOperationId() string          { if x != nil { return x.OperationId }; return "" }
func (x *PlanOperation) GetVmId() string                 { if x != nil { return x.VmId }; return "" }
func (x *PlanOperation) GetOperation() MicroVMOperation { if x != nil { return x.Operation }; return MicroVMOperation_MICRO_VM_OPERATION_UNSPECIFIED }

// CreateMicroVMConfig represents config for creating a microVM
type CreateMicroVMConfig struct {
	Name            string   `json:"name,omitempty"`
	VcpuCount       uint32   `json:"vcpu_count,omitempty"`
	MemoryMib       uint64   `json:"memory_mib,omitempty"`
	KernelImagePath string   `json:"kernel_image_path,omitempty"`
	RootfsPath      string   `json:"rootfs_path,omitempty"`
	CmdlineArgs     []string `json:"cmdline_args,omitempty"`
	NetIfaces       []string `json:"net_ifaces,omitempty"`
}

func (x *CreateMicroVMConfig) Reset() { *x = CreateMicroVMConfig{} }
func (*CreateMicroVMConfig) ProtoMessage() {}

// ExecutionUpdate represents an execution update
type ExecutionUpdate struct {
	ExecutionId  string                 `json:"execution_id,omitempty"`
	PlanId       string                 `json:"plan_id,omitempty"`
	OperationId  string                 `json:"operation_id,omitempty"`
	VmId         string                 `json:"vm_id,omitempty"`
	State        ExecutionState         `json:"state,omitempty"`
	ErrorCode    string                 `json:"error_code,omitempty"`
	ErrorMessage string                 `json:"error_message,omitempty"`
	UpdatedAt    *timestamppb.Timestamp `json:"updated_at,omitempty"`
}

func (x *ExecutionUpdate) Reset() { *x = ExecutionUpdate{} }
func (*ExecutionUpdate) ProtoMessage() {}

// StatusQueryRequest is the request for status query
type StatusQueryRequest struct {
	SiteId              string   `json:"site_id,omitempty"`
	HostIds             []string `json:"host_ids,omitempty"`
	VmIds               []string `json:"vm_ids,omitempty"`
	IncludeRecentLogs   bool     `json:"include_recent_logs,omitempty"`
	MaxLogsPerExecution int32    `json:"max_logs_per_execution,omitempty"`
}

func (x *StatusQueryRequest) Reset() { *x = StatusQueryRequest{} }
func (*StatusQueryRequest) ProtoMessage() {}

func (x *StatusQueryRequest) GetSiteId() string { if x != nil { return x.SiteId }; return "" }

// StatusQueryResponse is the response for status query
type StatusQueryResponse struct {
	Site       *SiteStatus       `json:"site,omitempty"`
	Hosts      []*HostStatus     `json:"hosts,omitempty"`
	Microvms   []*MicroVMStatus  `json:"microvms,omitempty"`
	Executions []*ExecutionStatus `json:"executions,omitempty"`
	RecentLogs []*ExecutionLog   `json:"recent_logs,omitempty"`
}

func (x *StatusQueryResponse) Reset() { *x = StatusQueryResponse{} }
func (*StatusQueryResponse) ProtoMessage() {}

func (x *StatusQueryResponse) GetSite() *SiteStatus { if x != nil { return x.Site }; return nil }
func (x *StatusQueryResponse) GetHosts() []*HostStatus { if x != nil { return x.Hosts }; return nil }
func (x *StatusQueryResponse) GetMicrovms() []*MicroVMStatus { if x != nil { return x.Microvms }; return nil }

// SiteStatus represents site status
type SiteStatus struct {
	SiteId            string                `json:"site_id,omitempty"`
	SiteName          string                `json:"site_name,omitempty"`
	ConnectivityState SiteConnectivityState `json:"connectivity_state,omitempty"`
	LastHeartbeatAt   *timestamppb.Timestamp `json:"last_heartbeat_at,omitempty"`
}

func (x *SiteStatus) Reset() { *x = SiteStatus{} }
func (*SiteStatus) ProtoMessage() {}

// HostStatus represents host status
type HostStatus struct {
	HostId          string              `json:"host_id,omitempty"`
	Hostname        string              `json:"hostname,omitempty"`
	AgentState      AgentLifecycleState `json:"agent_state,omitempty"`
	Capacity        *HostFacts          `json:"capacity,omitempty"`
	LastHeartbeatAt *timestamppb.Timestamp `json:"last_heartbeat_at,omitempty"`
}

func (x *HostStatus) Reset() { *x = HostStatus{} }
func (*HostStatus) ProtoMessage() {}

// MicroVMStatus represents microVM status
type MicroVMStatus struct {
	VmId      string                 `json:"vm_id,omitempty"`
	SiteId    string                 `json:"site_id,omitempty"`
	HostId    string                 `json:"host_id,omitempty"`
	Name      string                 `json:"name,omitempty"`
	State     MicroVMState           `json:"state,omitempty"`
	VcpuCount uint32                 `json:"vcpu_count,omitempty"`
	MemoryMib uint64                 `json:"memory_mib,omitempty"`
	UpdatedAt *timestamppb.Timestamp `json:"updated_at,omitempty"`
}

func (x *MicroVMStatus) Reset() { *x = MicroVMStatus{} }
func (*MicroVMStatus) ProtoMessage() {}

func (x *MicroVMStatus) GetVmId() string      { if x != nil { return x.VmId }; return "" }
func (x *MicroVMStatus) GetName() string      { if x != nil { return x.Name }; return "" }
func (x *MicroVMStatus) GetState() MicroVMState { if x != nil { return x.State }; return MicroVMState_MICRO_VM_STATE_UNSPECIFIED }
func (x *MicroVMStatus) GetVcpuCount() uint32 { if x != nil { return x.VcpuCount }; return 0 }
func (x *MicroVMStatus) GetMemoryMib() uint64 { if x != nil { return x.MemoryMib }; return 0 }

// ExecutionStatus represents execution status
type ExecutionStatus struct {
	ExecutionId  string                 `json:"execution_id,omitempty"`
	PlanId       string                 `json:"plan_id,omitempty"`
	OperationId  string                 `json:"operation_id,omitempty"`
	VmId         string                 `json:"vm_id,omitempty"`
	State        ExecutionState         `json:"state,omitempty"`
	ErrorMessage string                 `json:"error_message,omitempty"`
	UpdatedAt    *timestamppb.Timestamp `json:"updated_at,omitempty"`
}

func (x *ExecutionStatus) Reset() { *x = ExecutionStatus{} }
func (*ExecutionStatus) ProtoMessage() {}

// ExecutionLog represents an execution log entry
type ExecutionLog struct {
	ExecutionId string                 `json:"execution_id,omitempty"`
	Sequence    uint64                 `json:"sequence,omitempty"`
	Severity    LogSeverity            `json:"severity,omitempty"`
	Message     string                 `json:"message,omitempty"`
	EmittedAt   *timestamppb.Timestamp `json:"emitted_at,omitempty"`
}

func (x *ExecutionLog) Reset() { *x = ExecutionLog{} }
func (*ExecutionLog) ProtoMessage() {}

// LogFrame represents a log frame for streaming
type LogFrame struct {
	TenantId    string                 `json:"tenant_id,omitempty"`
	SiteId      string                 `json:"site_id,omitempty"`
	AgentId     string                 `json:"agent_id,omitempty"`
	PlanId      string                 `json:"plan_id,omitempty"`
	ExecutionId string                 `json:"execution_id,omitempty"`
	OperationId string                 `json:"operation_id,omitempty"`
	VmId        string                 `json:"vm_id,omitempty"`
	Sequence    uint64                 `json:"sequence,omitempty"`
	Severity    LogSeverity            `json:"severity,omitempty"`
	Message     string                 `json:"message,omitempty"`
	EmittedAt   *timestamppb.Timestamp `json:"emitted_at,omitempty"`
	Eof         bool                   `json:"eof,omitempty"`
}

func (x *LogFrame) Reset() { *x = LogFrame{} }
func (*LogFrame) ProtoMessage() {}

func (x *LogFrame) GetTenantId() string    { if x != nil { return x.TenantId }; return "" }
func (x *LogFrame) GetSiteId() string      { if x != nil { return x.SiteId }; return "" }
func (x *LogFrame) GetAgentId() string     { if x != nil { return x.AgentId }; return "" }
func (x *LogFrame) GetExecutionId() string { if x != nil { return x.ExecutionId }; return "" }
func (x *LogFrame) GetSequence() uint64    { if x != nil { return x.Sequence }; return 0 }
func (x *LogFrame) GetSeverity() LogSeverity { if x != nil { return x.Severity }; return LogSeverity_LOG_SEVERITY_UNSPECIFIED }
func (x *LogFrame) GetMessage() string     { if x != nil { return x.Message }; return "" }
func (x *LogFrame) GetEof() bool           { if x != nil { return x.Eof }; return false }

// StreamLogsResponse is the response for log streaming
type StreamLogsResponse struct {
	AcceptedFrames uint64 `json:"accepted_frames,omitempty"`
	DroppedFrames  uint64 `json:"dropped_frames,omitempty"`
}

func (x *StreamLogsResponse) Reset() { *x = StreamLogsResponse{} }
func (*StreamLogsResponse) ProtoMessage() {}

func (x *StreamLogsResponse) GetAcceptedFrames() uint64 { if x != nil { return x.AcceptedFrames }; return 0 }
func (x *StreamLogsResponse) GetDroppedFrames() uint64  { if x != nil { return x.DroppedFrames }; return 0 }

// File descriptor placeholder - not used but needed for interface compatibility
var File_api_proto_controlplane_v1_controlplane_proto = "placeholder"
