// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: api/proto/controlplane/v1/controlplane.proto

package controlplanev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires: gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EnrollmentService_Enroll_FullMethodName = "/nkudo.controlplane.v1.EnrollmentService/Enroll"
)

// EnrollmentServiceClient is the client API for EnrollmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnrollmentServiceClient interface {
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
}

type enrollmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnrollmentServiceClient(cc grpc.ClientConnInterface) EnrollmentServiceClient {
	return &enrollmentServiceClient{cc}
}

func (c *enrollmentServiceClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, EnrollmentService_Enroll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnrollmentServiceServer is the server API for EnrollmentService service.
// All implementations must embed UnimplementedEnrollmentServiceServer
// for forward compatibility
type EnrollmentServiceServer interface {
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	mustEmbedUnimplementedEnrollmentServiceServer()
}

// UnimplementedEnrollmentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEnrollmentServiceServer struct {
}

func (UnimplementedEnrollmentServiceServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedEnrollmentServiceServer) mustEmbedUnimplementedEnrollmentServiceServer() {}

// UnsafeEnrollmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnrollmentServiceServer will
// result in compilation errors.
type UnsafeEnrollmentServiceServer interface {
	mustEmbedUnimplementedEnrollmentServiceServer()
}

func RegisterEnrollmentServiceServer(s grpc.ServiceRegistrar, srv EnrollmentServiceServer) {
	s.RegisterService(&EnrollmentService_ServiceDesc, srv)
}

func _EnrollmentService_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnrollmentService_ServiceDesc is the grpc.ServiceDesc for EnrollmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnrollmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nkudo.controlplane.v1.EnrollmentService",
	HandlerType: (*EnrollmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _EnrollmentService_Enroll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/controlplane/v1/controlplane.proto",
}

const (
	AgentControlService_Heartbeat_FullMethodName = "/nkudo.controlplane.v1.AgentControlService/Heartbeat"
	AgentControlService_StreamLogs_FullMethodName = "/nkudo.controlplane.v1.AgentControlService/StreamLogs"
)

// AgentControlServiceClient is the client API for AgentControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentControlServiceClient interface {
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (AgentControlService_StreamLogsClient, error)
}

type agentControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentControlServiceClient(cc grpc.ClientConnInterface) AgentControlServiceClient {
	return &agentControlServiceClient{cc}
}

func (c *agentControlServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, AgentControlService_Heartbeat_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlServiceClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (AgentControlService_StreamLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentControlService_ServiceDesc.Streams[0], AgentControlService_StreamLogs_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &agentControlServiceStreamLogsClient{stream}
	return x, nil
}

type AgentControlService_StreamLogsClient interface {
	Send(*LogFrame) error
	CloseAndRecv() (*StreamLogsResponse, error)
	grpc.ClientStream
}

type agentControlServiceStreamLogsClient struct {
	grpc.ClientStream
}

func (x *agentControlServiceStreamLogsClient) Send(m *LogFrame) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentControlServiceStreamLogsClient) CloseAndRecv() (*StreamLogsResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StreamLogsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentControlServiceServer is the server API for AgentControlService service.
// All implementations must embed UnimplementedAgentControlServiceServer
// for forward compatibility
type AgentControlServiceServer interface {
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	StreamLogs(AgentControlService_StreamLogsServer) error
	mustEmbedUnimplementedAgentControlServiceServer()
}

// UnimplementedAgentControlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAgentControlServiceServer struct {
}

func (UnimplementedAgentControlServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAgentControlServiceServer) StreamLogs(AgentControlService_StreamLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedAgentControlServiceServer) mustEmbedUnimplementedAgentControlServiceServer() {}

// UnsafeAgentControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentControlServiceServer will
// result in compilation errors.
type UnsafeAgentControlServiceServer interface {
	mustEmbedUnimplementedAgentControlServiceServer()
}

func RegisterAgentControlServiceServer(s grpc.ServiceRegistrar, srv AgentControlServiceServer) {
	s.RegisterService(&AgentControlService_ServiceDesc, srv)
}

func _AgentControlService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControlService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControlService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentControlServiceServer).StreamLogs(&agentControlServiceStreamLogsServer{stream})
}

type AgentControlService_StreamLogsServer interface {
	SendAndClose(*StreamLogsResponse) error
	Recv() (*LogFrame, error)
	grpc.ServerStream
}

type agentControlServiceStreamLogsServer struct {
	grpc.ServerStream
}

func (x *agentControlServiceStreamLogsServer) SendAndClose(m *StreamLogsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentControlServiceStreamLogsServer) Recv() (*LogFrame, error) {
	m := new(LogFrame)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentControlService_ServiceDesc is the grpc.ServiceDesc for AgentControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nkudo.controlplane.v1.AgentControlService",
	HandlerType: (*AgentControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _AgentControlService_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _AgentControlService_StreamLogs_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/controlplane/v1/controlplane.proto",
}

const (
	TenantControlService_ApplyPlan_FullMethodName = "/nkudo.controlplane.v1.TenantControlService/ApplyPlan"
	TenantControlService_GetStatus_FullMethodName = "/nkudo.controlplane.v1.TenantControlService/GetStatus"
)

// TenantControlServiceClient is the client API for TenantControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TenantControlServiceClient interface {
	ApplyPlan(ctx context.Context, in *ApplyPlanRequest, opts ...grpc.CallOption) (*ApplyPlanResponse, error)
	GetStatus(ctx context.Context, in *StatusQueryRequest, opts ...grpc.CallOption) (*StatusQueryResponse, error)
}

type tenantControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantControlServiceClient(cc grpc.ClientConnInterface) TenantControlServiceClient {
	return &tenantControlServiceClient{cc}
}

func (c *tenantControlServiceClient) ApplyPlan(ctx context.Context, in *ApplyPlanRequest, opts ...grpc.CallOption) (*ApplyPlanResponse, error) {
	out := new(ApplyPlanResponse)
	err := c.cc.Invoke(ctx, TenantControlService_ApplyPlan_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantControlServiceClient) GetStatus(ctx context.Context, in *StatusQueryRequest, opts ...grpc.CallOption) (*StatusQueryResponse, error) {
	out := new(StatusQueryResponse)
	err := c.cc.Invoke(ctx, TenantControlService_GetStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantControlServiceServer is the server API for TenantControlService service.
// All implementations must embed UnimplementedTenantControlServiceServer
// for forward compatibility
type TenantControlServiceServer interface {
	ApplyPlan(context.Context, *ApplyPlanRequest) (*ApplyPlanResponse, error)
	GetStatus(context.Context, *StatusQueryRequest) (*StatusQueryResponse, error)
	mustEmbedUnimplementedTenantControlServiceServer()
}

// UnimplementedTenantControlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTenantControlServiceServer struct {
}

func (UnimplementedTenantControlServiceServer) ApplyPlan(context.Context, *ApplyPlanRequest) (*ApplyPlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyPlan not implemented")
}
func (UnimplementedTenantControlServiceServer) GetStatus(context.Context, *StatusQueryRequest) (*StatusQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedTenantControlServiceServer) mustEmbedUnimplementedTenantControlServiceServer() {}

// UnsafeTenantControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantControlServiceServer will
// result in compilation errors.
type UnsafeTenantControlServiceServer interface {
	mustEmbedUnimplementedTenantControlServiceServer()
}

func RegisterTenantControlServiceServer(s grpc.ServiceRegistrar, srv TenantControlServiceServer) {
	s.RegisterService(&TenantControlService_ServiceDesc, srv)
}

func _TenantControlService_ApplyPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantControlServiceServer).ApplyPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantControlService_ApplyPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantControlServiceServer).ApplyPlan(ctx, req.(*ApplyPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantControlService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantControlServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantControlService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantControlServiceServer).GetStatus(ctx, req.(*StatusQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TenantControlService_ServiceDesc is the grpc.ServiceDesc for TenantControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TenantControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nkudo.controlplane.v1.TenantControlService",
	HandlerType: (*TenantControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyPlan",
			Handler:    _TenantControlService_ApplyPlan_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _TenantControlService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/controlplane/v1/controlplane.proto",
}
